# Indicates compatibility version with lifecycle
api = "0.7"

[buildpack]
description = "A Cloud Native Buildpack that installs and executes `rustup` to install Rust"
homepage = "https://github.com/zouyuxuan/scarb"
id = "paketo-community/scarb"
keywords = ["cairo", "scarb"]
name = "Paketo Buildpack for Scarb"
sbom-formats = ["application/vnd.cyclonedx+json", "application/vnd.syft+json"]
version = "{{.version}}"

[[buildpack.licenses]]
type = "Apache-2.0"
uri = "https://github.com/paketo-community/scarb/blob/main/LICENSE"

[metadata]
include-files = ["LICENSE", "NOTICE", "README.md", "bin/build", "bin/detect", "bin/main", "buildpack.toml"]
pre-package = "scripts/build.sh"


[[metadata.dependencies]]
id = "scarb-init"
name = "Scarb"
purl = "pkg:generic/scarb@2.4.3"
sha256 = "0c80edd932b21308fd024a2474f2db4647c25124557737fa0facfd902fd39f53"
source = "https://github.com/software-mansion/scarb/releases/download/v2.4.3/scarb-v2.4.3-x86_64-unknown-linux-musl.tar.gz"
source-sha256 = "0c80edd932b21308fd024a2474f2db4647c25124557737fa0facfd902fd39f53"
stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "*"]
uri = "https://github.com/software-mansion/scarb/releases/download/v2.4.3/scarb-v2.4.3-x86_64-unknown-linux-musl.tar.gz"
version = "2.4.3"

[[metadata.dependencies.licenses]]
type = "Apache-2.0"
uri = "https://github.com/rust-lang/rustup/blob/master/LICENSE-APACHE"

[[metadata.dependencies.licenses]]
type = "MIT"
uri = "https://github.com/rust-lang/rustup/blob/master/LICENSE-MIT"


[[stacks]]
id = "*"
